### ISSUE TITLE
Reply to

### ISSUE THREAD

**Issue by Moorst** [ThemeFuse/Unyson-Mailer-Extension#4]
Is it possible to automatically set the reply-to header to the email address provided in the contact form?

I don't mind having to hack this in myself for a quick-fix. I believe it's being set with the following code in includes/send-methods/class-fw-ext-mailer-send-method-wpmail.php;

```
if (method_exists($email, 'get_reply_to') && $email->get_reply_to()) {
	if (is_array($email->get_reply_to())) {
		foreach ($email->get_reply_to() as $_address => $_name) {
			$headers[] = 'Reply-To:'. $this->make_email_header($_address, $_name);
		}
	} else {
		$headers[] = 'Reply-To:'. $this->make_email_header($email->get_reply_to(), '');
	}
}
```

Can you advise how I could pick up the address from the email field? Thanks.

**Comment by ViorelEremia** [comment]
You mean that?: https://github.com/ThemeFuse/Unyson/issues/2920

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
